<?php
header("Access-Control-Allow-Origin: *");

$movies = [
    "count"=>5,
    "start"=>0,
    "total"=>20,
    "subjects"=>[
        [
            "rating"=>[
                "max"=>10,
                "average"=>0,
                "stars"=>"00",
                "min"=>0
            ],
            "genres"=>[
                "剧情",
                "爱情"
            ],
            "title"=>"缘·梦",
            "casts"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1406533/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/f/movie/ca527386eb8c4e325611e22dfcb04cc116d6b423/pics/movie/celebrity-default-small.png",
                        "large"=>"https://img3.doubanio.com/f/movie/63acc16ca6309ef191f0378faf793d1096a3e606/pics/movie/celebrity-default-large.png",
                        "medium"=>"https://img1.doubanio.com/f/movie/8dd0c794499fe925ae2ae89ee30cd225750457b4/pics/movie/celebrity-default-medium.png"
                    ],
                    "name"=>"高蕊",
                    "id"=>"1406533"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1371228/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/f/movie/ca527386eb8c4e325611e22dfcb04cc116d6b423/pics/movie/celebrity-default-small.png",
                        "large"=>"https://img3.doubanio.com/f/movie/63acc16ca6309ef191f0378faf793d1096a3e606/pics/movie/celebrity-default-large.png",
                        "medium"=>"https://img1.doubanio.com/f/movie/8dd0c794499fe925ae2ae89ee30cd225750457b4/pics/movie/celebrity-default-medium.png"
                    ],
                    "name"=>"刘滨",
                    "id"=>"1371228"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1325200/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1386916328.14.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1386916328.14.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1386916328.14.jpg"
                    ],
                    "name"=>"张津赫",
                    "id"=>"1325200"
                ]
            ],
            "collect_count"=>5,
            "original_title"=>"缘·梦",
            "subtype"=>"movie",
            "directors"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1406531/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/f/movie/ca527386eb8c4e325611e22dfcb04cc116d6b423/pics/movie/celebrity-default-small.png",
                        "large"=>"https://img3.doubanio.com/f/movie/63acc16ca6309ef191f0378faf793d1096a3e606/pics/movie/celebrity-default-large.png",
                        "medium"=>"https://img1.doubanio.com/f/movie/8dd0c794499fe925ae2ae89ee30cd225750457b4/pics/movie/celebrity-default-medium.png"
                    ],
                    "name"=>"冯铁成",
                    "id"=>"1406531"
                ]
            ],
            "year"=>"2018",
            "images"=>[
                "small"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541120716.jpg",
                "large"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541120716.jpg",
                "medium"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541120716.jpg"
            ],
            "alt"=>"https://movie.douban.com/subject/30389564/",
            "id"=>"30389564"
        ],
        [
            "rating"=>[
                "max"=>10,
                "average"=>8.5,
                "stars"=>"45",
                "min"=>0
            ],
            "genres"=>[
                "剧情",
                "犯罪",
                "悬疑"
            ],
            "title"=>"网络谜踪",
            "casts"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1019015/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1328.jpg",
                        "large"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1328.jpg",
                        "medium"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1328.jpg"
                    ],
                    "name"=>"约翰·赵",
                    "id"=>"1019015"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1393518/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1534082266.94.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1534082266.94.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1534082266.94.jpg"
                    ],
                    "name"=>"米切尔·拉",
                    "id"=>"1393518"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1022653/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p24903.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p24903.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p24903.jpg"
                    ],
                    "name"=>"黛博拉·梅辛",
                    "id"=>"1022653"
                ]
            ],
            "collect_count"=>153978,
            "original_title"=>"Searching",
            "subtype"=>"movie",
            "directors"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1393516/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543483760.83.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543483760.83.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543483760.83.jpg"
                    ],
                    "name"=>"阿尼什·查甘蒂",
                    "id"=>"1393516"
                ]
            ],
            "year"=>"2018",
            "images"=>[
                "small"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541019743.jpg",
                "large"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541019743.jpg",
                "medium"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541019743.jpg"
            ],
            "alt"=>"https://movie.douban.com/subject/27615441/",
            "id"=>"27615441"
        ],
        [
            "rating"=>[
                "max"=>10,
                "average"=>9.1,
                "stars"=>"45",
                "min"=>0
            ],
            "genres"=>[
                "动画",
                "奇幻",
                "冒险"
            ],
            "title"=>"龙猫",
            "casts"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1019382/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1455201170.02.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1455201170.02.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1455201170.02.jpg"
                    ],
                    "name"=>"日高法子",
                    "id"=>"1019382"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1025582/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p29537.jpg",
                        "large"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p29537.jpg",
                        "medium"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p29537.jpg"
                    ],
                    "name"=>"坂本千夏",
                    "id"=>"1025582"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1379738/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1503457262.72.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1503457262.72.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1503457262.72.jpg"
                    ],
                    "name"=>"糸井重里",
                    "id"=>"1379738"
                ]
            ],
            "collect_count"=>716035,
            "original_title"=>"となりのトトロ",
            "subtype"=>"movie",
            "directors"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1054439/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p616.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p616.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p616.jpg"
                    ],
                    "name"=>"宫崎骏",
                    "id"=>"1054439"
                ]
            ],
            "year"=>"1988",
            "images"=>[
                "small"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2540924496.jpg",
                "large"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2540924496.jpg",
                "medium"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2540924496.jpg"
            ],
            "alt"=>"https://movie.douban.com/subject/1291560/",
            "id"=>"1291560"
        ],
        [
            "rating"=>[
                "max"=>10,
                "average"=>7.6,
                "stars"=>"40",
                "min"=>0
            ],
            "genres"=>[
                "剧情",
                "喜剧",
                "传记"
            ],
            "title"=>"印度合伙人",
            "casts"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1049615/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p7474.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p7474.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p7474.jpg"
                    ],
                    "name"=>"阿克谢·库玛尔",
                    "id"=>"1049615"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1329473/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1486452827.09.jpg",
                        "large"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1486452827.09.jpg",
                        "medium"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1486452827.09.jpg"
                    ],
                    "name"=>"拉迪卡·艾普特",
                    "id"=>"1329473"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1018143/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1402744446.01.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1402744446.01.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1402744446.01.jpg"
                    ],
                    "name"=>"索娜姆·卡普尔",
                    "id"=>"1018143"
                ]
            ],
            "collect_count"=>8839,
            "original_title"=>"Padman",
            "subtype"=>"movie",
            "directors"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1311506/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1373516277.14.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1373516277.14.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1373516277.14.jpg"
                    ],
                    "name"=>"R·巴尔基",
                    "id"=>"1311506"
                ]
            ],
            "year"=>"2018",
            "images"=>[
                "small"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2540940050.jpg",
                "large"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2540940050.jpg",
                "medium"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2540940050.jpg"
            ],
            "alt"=>"https://movie.douban.com/subject/27198855/",
            "id"=>"27198855"
        ],
        [
            "rating"=>[
                "max"=>10,
                "average"=>6.5,
                "stars"=>"35",
                "min"=>0
            ],
            "genres"=>[
                "喜剧",
                "动画"
            ],
            "title"=>"绿毛怪格林奇",
            "casts"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1009405/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p41072.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p41072.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p41072.jpg"
                    ],
                    "name"=>"本尼迪克特·康伯巴奇",
                    "id"=>"1009405"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1387860/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1517222739.45.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1517222739.45.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1517222739.45.jpg"
                    ],
                    "name"=>"卡梅伦·丝蕾",
                    "id"=>"1387860"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1031815/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p32735.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p32735.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p32735.jpg"
                    ],
                    "name"=>"拉什达·琼斯",
                    "id"=>"1031815"
                ]
            ],
            "collect_count"=>1253,
            "original_title"=>"The Grinch",
            "subtype"=>"movie",
            "directors"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1280591/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1467266335.21.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1467266335.21.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1467266335.21.jpg"
                    ],
                    "name"=>"亚罗·切尼",
                    "id"=>"1280591"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1032291/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p34173.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p34173.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p34173.jpg"
                    ],
                    "name"=>"斯科特·摩西尔",
                    "id"=>"1032291"
                ]
            ],
            "year"=>"2018",
            "images"=>[
                "small"=>"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2539666559.jpg",
                "large"=>"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2539666559.jpg",
                "medium"=>"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2539666559.jpg"
            ],
            "alt"=>"https://movie.douban.com/subject/23774869/",
            "id"=>"23774869"
        ],
        [
            "rating"=>[
                "max"=>10,
                "average"=>0,
                "stars"=>"00",
                "min"=>0
            ],
            "genres"=>[
                "剧情"
            ],
            "title"=>"春天的马拉松",
            "casts"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1275537/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1417873574.38.jpg",
                        "large"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1417873574.38.jpg",
                        "medium"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1417873574.38.jpg"
                    ],
                    "name"=>"张铎",
                    "id"=>"1275537"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1317855/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p41469.jpg",
                        "large"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p41469.jpg",
                        "medium"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p41469.jpg"
                    ],
                    "name"=>"郑昊",
                    "id"=>"1317855"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1316554/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1464867372.56.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1464867372.56.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1464867372.56.jpg"
                    ],
                    "name"=>"徐百卉",
                    "id"=>"1316554"
                ]
            ],
            "collect_count"=>11,
            "original_title"=>"春天的马拉松",
            "subtype"=>"movie",
            "directors"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1324843/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1473680438.59.jpg",
                        "large"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1473680438.59.jpg",
                        "medium"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1473680438.59.jpg"
                    ],
                    "name"=>"夏晓昀",
                    "id"=>"1324843"
                ]
            ],
            "year"=>"2018",
            "images"=>[
                "small"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2540564044.jpg",
                "large"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2540564044.jpg",
                "medium"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2540564044.jpg"
            ],
            "alt"=>"https://movie.douban.com/subject/30304044/",
            "id"=>"30304044"
        ],
        [
            "rating"=>[
                "max"=>10,
                "average"=>0,
                "stars"=>"00",
                "min"=>0
            ],
            "genres"=>[
                "喜剧",
                "动作",
                "冒险"
            ],
            "title"=>"最萌警探",
            "casts"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1101813/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1406299075.37.jpg",
                        "large"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1406299075.37.jpg",
                        "medium"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1406299075.37.jpg"
                    ],
                    "name"=>"谢尔盖·加尔马什",
                    "id"=>"1101813"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1405412/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1544522001.24.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1544522001.24.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1544522001.24.jpg"
                    ],
                    "name"=>"安德烈·纳兹莫夫 ",
                    "id"=>"1405412"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1192229/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p20506.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p20506.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p20506.jpg"
                    ],
                    "name"=>"莉莎·阿尔扎马索娃",
                    "id"=>"1192229"
                ]
            ],
            "collect_count"=>7,
            "original_title"=>"Напарник",
            "subtype"=>"movie",
            "directors"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1405411/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/f/movie/ca527386eb8c4e325611e22dfcb04cc116d6b423/pics/movie/celebrity-default-small.png",
                        "large"=>"https://img3.doubanio.com/f/movie/63acc16ca6309ef191f0378faf793d1096a3e606/pics/movie/celebrity-default-large.png",
                        "medium"=>"https://img1.doubanio.com/f/movie/8dd0c794499fe925ae2ae89ee30cd225750457b4/pics/movie/celebrity-default-medium.png"
                    ],
                    "name"=>"亚历山大·安德里尤先科",
                    "id"=>"1405411"
                ]
            ],
            "year"=>"2017",
            "images"=>[
                "small"=>"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2541098388.jpg",
                "large"=>"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2541098388.jpg",
                "medium"=>"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2541098388.jpg"
            ],
            "alt"=>"https://movie.douban.com/subject/30387535/",
            "id"=>"30387535"
        ],
        [
            "rating"=>[
                "max"=>10,
                "average"=>0,
                "stars"=>"00",
                "min"=>0
            ],
            "genres"=>[
                "惊悚",
                "恐怖"
            ],
            "title"=>"午夜整容室",
            "casts"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1405474/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543374431.81.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543374431.81.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543374431.81.jpg"
                    ],
                    "name"=>"赖晶晶",
                    "id"=>"1405474"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1323199/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p55825.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p55825.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p55825.jpg"
                    ],
                    "name"=>"王李丹妮",
                    "id"=>"1323199"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1351929/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/f/movie/ca527386eb8c4e325611e22dfcb04cc116d6b423/pics/movie/celebrity-default-small.png",
                        "large"=>"https://img3.doubanio.com/f/movie/63acc16ca6309ef191f0378faf793d1096a3e606/pics/movie/celebrity-default-large.png",
                        "medium"=>"https://img1.doubanio.com/f/movie/8dd0c794499fe925ae2ae89ee30cd225750457b4/pics/movie/celebrity-default-medium.png"
                    ],
                    "name"=>"陈垚",
                    "id"=>"1351929"
                ]
            ],
            "collect_count"=>32,
            "original_title"=>"午夜整容室",
            "subtype"=>"movie",
            "directors"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1405475/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543374523.84.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543374523.84.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543374523.84.jpg"
                    ],
                    "name"=>"曹志鹏",
                    "id"=>"1405475"
                ]
            ],
            "year"=>"2018",
            "images"=>[
                "small"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2538063852.jpg",
                "large"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2538063852.jpg",
                "medium"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2538063852.jpg"
            ],
            "alt"=>"https://movie.douban.com/subject/30296766/",
            "id"=>"30296766"
        ],
        [
            "rating"=>[
                "max"=>10,
                "average"=>0,
                "stars"=>"00",
                "min"=>0
            ],
            "genres"=>[
                "剧情",
                "喜剧"
            ],
            "title"=>"来日方长",
            "casts"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1401609/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1538038550.32.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1538038550.32.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1538038550.32.jpg"
                    ],
                    "name"=>"孙聪",
                    "id"=>"1401609"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1274928/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p7939.jpg",
                        "large"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p7939.jpg",
                        "medium"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p7939.jpg"
                    ],
                    "name"=>"李明",
                    "id"=>"1274928"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1372924/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1493509715.09.jpg",
                        "large"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1493509715.09.jpg",
                        "medium"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1493509715.09.jpg"
                    ],
                    "name"=>"于又川",
                    "id"=>"1372924"
                ]
            ],
            "collect_count"=>7,
            "original_title"=>"来日方长",
            "subtype"=>"movie",
            "directors"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1404752/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1542692077.55.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1542692077.55.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1542692077.55.jpg"
                    ],
                    "name"=>"刘德强",
                    "id"=>"1404752"
                ]
            ],
            "year"=>"2018",
            "images"=>[
                "small"=>"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2540298697.jpg",
                "large"=>"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2540298697.jpg",
                "medium"=>"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2540298697.jpg"
            ],
            "alt"=>"https://movie.douban.com/subject/30381822/",
            "id"=>"30381822"
        ],
        [
            "rating"=>[
                "max"=>10,
                "average"=>0,
                "stars"=>"00",
                "min"=>0
            ],
            "genres"=>[
                "剧情",
                "喜剧",
                "家庭"
            ],
            "title"=>"二胎来了",
            "casts"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1326226/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1358397915.06.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1358397915.06.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1358397915.06.jpg"
                    ],
                    "name"=>"郭常辉",
                    "id"=>"1326226"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1363837/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1477490675.28.jpg",
                        "large"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1477490675.28.jpg",
                        "medium"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1477490675.28.jpg"
                    ],
                    "name"=>"栗梅",
                    "id"=>"1363837"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1318762/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1478678359.13.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1478678359.13.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1478678359.13.jpg"
                    ],
                    "name"=>"祁映诺",
                    "id"=>"1318762"
                ]
            ],
            "collect_count"=>16,
            "original_title"=>"二胎来了",
            "subtype"=>"movie",
            "directors"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1399601/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1534919717.25.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1534919717.25.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1534919717.25.jpg"
                    ],
                    "name"=>"郑成飞",
                    "id"=>"1399601"
                ]
            ],
            "year"=>"2018",
            "images"=>[
                "small"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2540923720.jpg",
                "large"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2540923720.jpg",
                "medium"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2540923720.jpg"
            ],
            "alt"=>"https://movie.douban.com/subject/26974343/",
            "id"=>"26974343"
        ],
        [
            "rating"=>[
                "max"=>10,
                "average"=>0,
                "stars"=>"00",
                "min"=>0
            ],
            "genres"=>[
                "剧情"
            ],
            "title"=>"正好的我们",
            "casts"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1336952/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543550793.46.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543550793.46.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543550793.46.jpg"
                    ],
                    "name"=>"马歌",
                    "id"=>"1336952"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1350716/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543550844.35.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543550844.35.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543550844.35.jpg"
                    ],
                    "name"=>"李岱昆",
                    "id"=>"1350716"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1350717/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543550922.73.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543550922.73.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543550922.73.jpg"
                    ],
                    "name"=>"陆妍淇",
                    "id"=>"1350717"
                ]
            ],
            "collect_count"=>7,
            "original_title"=>"正好的我们",
            "subtype"=>"movie",
            "directors"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1379978/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/f/movie/ca527386eb8c4e325611e22dfcb04cc116d6b423/pics/movie/celebrity-default-small.png",
                        "large"=>"https://img3.doubanio.com/f/movie/63acc16ca6309ef191f0378faf793d1096a3e606/pics/movie/celebrity-default-large.png",
                        "medium"=>"https://img1.doubanio.com/f/movie/8dd0c794499fe925ae2ae89ee30cd225750457b4/pics/movie/celebrity-default-medium.png"
                    ],
                    "name"=>"赵震浩",
                    "id"=>"1379978"
                ]
            ],
            "year"=>"2018",
            "images"=>[
                "small"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541280456.jpg",
                "large"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541280456.jpg",
                "medium"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541280456.jpg"
            ],
            "alt"=>"https://movie.douban.com/subject/26574964/",
            "id"=>"26574964"
        ],
        [
            "rating"=>[
                "max"=>10,
                "average"=>0,
                "stars"=>"00",
                "min"=>0
            ],
            "genres"=>[
                "剧情"
            ],
            "title"=>"轻轻握住你的手",
            "casts"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1339766/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1542967775.01.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1542967775.01.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1542967775.01.jpg"
                    ],
                    "name"=>"郭纬",
                    "id"=>"1339766"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1349269/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1542967815.38.jpg",
                        "large"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1542967815.38.jpg",
                        "medium"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1542967815.38.jpg"
                    ],
                    "name"=>"马藜",
                    "id"=>"1349269"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1405164/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1542967833.12.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1542967833.12.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1542967833.12.jpg"
                    ],
                    "name"=>"卡奇",
                    "id"=>"1405164"
                ]
            ],
            "collect_count"=>3,
            "original_title"=>"轻轻握住你的手",
            "subtype"=>"movie",
            "directors"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1405163/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543202513.84.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543202513.84.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543202513.84.jpg"
                    ],
                    "name"=>"张健伟",
                    "id"=>"1405163"
                ]
            ],
            "year"=>"2018",
            "images"=>[
                "small"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2540671661.jpg",
                "large"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2540671661.jpg",
                "medium"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2540671661.jpg"
            ],
            "alt"=>"https://movie.douban.com/subject/27611675/",
            "id"=>"27611675"
        ],
        [
            "rating"=>[
                "max"=>10,
                "average"=>0,
                "stars"=>"00",
                "min"=>0
            ],
            "genres"=>[
                "动作",
                "爱情",
                "武侠"
            ],
            "title"=>"铁臂双雄",
            "casts"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1342563/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1523847512.2.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1523847512.2.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1523847512.2.jpg"
                    ],
                    "name"=>"何翔",
                    "id"=>"1342563"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1404604/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1542342590.25.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1542342590.25.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1542342590.25.jpg"
                    ],
                    "name"=>"张永华",
                    "id"=>"1404604"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1396301/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1530090252.15.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1530090252.15.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1530090252.15.jpg"
                    ],
                    "name"=>"陈超 ",
                    "id"=>"1396301"
                ]
            ],
            "collect_count"=>3,
            "original_title"=>"铁臂双雄",
            "subtype"=>"movie",
            "directors"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1328733/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/f/movie/ca527386eb8c4e325611e22dfcb04cc116d6b423/pics/movie/celebrity-default-small.png",
                        "large"=>"https://img3.doubanio.com/f/movie/63acc16ca6309ef191f0378faf793d1096a3e606/pics/movie/celebrity-default-large.png",
                        "medium"=>"https://img1.doubanio.com/f/movie/8dd0c794499fe925ae2ae89ee30cd225750457b4/pics/movie/celebrity-default-medium.png"
                    ],
                    "name"=>"苗述",
                    "id"=>"1328733"
                ]
            ],
            "year"=>"2018",
            "images"=>[
                "small"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2540029076.jpg",
                "large"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2540029076.jpg",
                "medium"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2540029076.jpg"
            ],
            "alt"=>"https://movie.douban.com/subject/30379636/",
            "id"=>"30379636"
        ],
        [
            "rating"=>[
                "max"=>10,
                "average"=>0,
                "stars"=>"00",
                "min"=>0
            ],
            "genres"=>[
                "喜剧",
                "悬疑"
            ],
            "title"=>"堡藏",
            "casts"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1406571/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/f/movie/ca527386eb8c4e325611e22dfcb04cc116d6b423/pics/movie/celebrity-default-small.png",
                        "large"=>"https://img3.doubanio.com/f/movie/63acc16ca6309ef191f0378faf793d1096a3e606/pics/movie/celebrity-default-large.png",
                        "medium"=>"https://img1.doubanio.com/f/movie/8dd0c794499fe925ae2ae89ee30cd225750457b4/pics/movie/celebrity-default-medium.png"
                    ],
                    "name"=>"朗贵钧",
                    "id"=>"1406571"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1406572/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/f/movie/ca527386eb8c4e325611e22dfcb04cc116d6b423/pics/movie/celebrity-default-small.png",
                        "large"=>"https://img3.doubanio.com/f/movie/63acc16ca6309ef191f0378faf793d1096a3e606/pics/movie/celebrity-default-large.png",
                        "medium"=>"https://img1.doubanio.com/f/movie/8dd0c794499fe925ae2ae89ee30cd225750457b4/pics/movie/celebrity-default-medium.png"
                    ],
                    "name"=>"甘林熠",
                    "id"=>"1406572"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1406575/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/f/movie/ca527386eb8c4e325611e22dfcb04cc116d6b423/pics/movie/celebrity-default-small.png",
                        "large"=>"https://img3.doubanio.com/f/movie/63acc16ca6309ef191f0378faf793d1096a3e606/pics/movie/celebrity-default-large.png",
                        "medium"=>"https://img1.doubanio.com/f/movie/8dd0c794499fe925ae2ae89ee30cd225750457b4/pics/movie/celebrity-default-medium.png"
                    ],
                    "name"=>"安赛龙",
                    "id"=>"1406575"
                ]
            ],
            "collect_count"=>0,
            "original_title"=>"堡藏",
            "subtype"=>"movie",
            "directors"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1351881/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1500703834.3.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1500703834.3.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1500703834.3.jpg"
                    ],
                    "name"=>"刘峰",
                    "id"=>"1351881"
                ]
            ],
            "year"=>"2018",
            "images"=>[
                "small"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541305120.jpg",
                "large"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541305120.jpg",
                "medium"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541305120.jpg"
            ],
            "alt"=>"https://movie.douban.com/subject/26958765/",
            "id"=>"26958765"
        ],
        [
            "rating"=>[
                "max"=>10,
                "average"=>0,
                "stars"=>"00",
                "min"=>0
            ],
            "genres"=>[
                "剧情"
            ],
            "title"=>"破天荒",
            "casts"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1315699/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p33228.jpg",
                        "large"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p33228.jpg",
                        "medium"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p33228.jpg"
                    ],
                    "name"=>"晋松",
                    "id"=>"1315699"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1352133/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1459243623.68.jpg",
                        "large"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1459243623.68.jpg",
                        "medium"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1459243623.68.jpg"
                    ],
                    "name"=>"草莓",
                    "id"=>"1352133"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1346036/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/f/movie/ca527386eb8c4e325611e22dfcb04cc116d6b423/pics/movie/celebrity-default-small.png",
                        "large"=>"https://img3.doubanio.com/f/movie/63acc16ca6309ef191f0378faf793d1096a3e606/pics/movie/celebrity-default-large.png",
                        "medium"=>"https://img1.doubanio.com/f/movie/8dd0c794499fe925ae2ae89ee30cd225750457b4/pics/movie/celebrity-default-medium.png"
                    ],
                    "name"=>"Vander McLeod",
                    "id"=>"1346036"
                ]
            ],
            "collect_count"=>1,
            "original_title"=>"破天荒",
            "subtype"=>"movie",
            "directors"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1406583/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/f/movie/ca527386eb8c4e325611e22dfcb04cc116d6b423/pics/movie/celebrity-default-small.png",
                        "large"=>"https://img3.doubanio.com/f/movie/63acc16ca6309ef191f0378faf793d1096a3e606/pics/movie/celebrity-default-large.png",
                        "medium"=>"https://img1.doubanio.com/f/movie/8dd0c794499fe925ae2ae89ee30cd225750457b4/pics/movie/celebrity-default-medium.png"
                    ],
                    "name"=>"罗金耀",
                    "id"=>"1406583"
                ]
            ],
            "year"=>"2018",
            "images"=>[
                "small"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2542293271.jpg",
                "large"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2542293271.jpg",
                "medium"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2542293271.jpg"
            ],
            "alt"=>"https://movie.douban.com/subject/30400719/",
            "id"=>"30400719"
        ],
        [
            "rating"=>[
                "max"=>10,
                "average"=>6.6,
                "stars"=>"35",
                "min"=>0
            ],
            "genres"=>[
                "剧情",
                "悬疑"
            ],
            "title"=>"淡蓝琥珀",
            "casts"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1346550/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1505213224.8.jpg",
                        "large"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1505213224.8.jpg",
                        "medium"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1505213224.8.jpg"
                    ],
                    "name"=>"王真儿",
                    "id"=>"1346550"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1274390/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p33149.jpg",
                        "large"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p33149.jpg",
                        "medium"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p33149.jpg"
                    ],
                    "name"=>"吕聿来",
                    "id"=>"1274390"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1274576/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1370503685.74.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1370503685.74.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1370503685.74.jpg"
                    ],
                    "name"=>"耿乐",
                    "id"=>"1274576"
                ]
            ],
            "collect_count"=>360,
            "original_title"=>"淡蓝琥珀",
            "subtype"=>"movie",
            "directors"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1381116/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1527068725.8.jpg",
                        "large"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1527068725.8.jpg",
                        "medium"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1527068725.8.jpg"
                    ],
                    "name"=>"周劼",
                    "id"=>"1381116"
                ]
            ],
            "year"=>"2018",
            "images"=>[
                "small"=>"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2542212488.jpg",
                "large"=>"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2542212488.jpg",
                "medium"=>"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2542212488.jpg"
            ],
            "alt"=>"https://movie.douban.com/subject/27069377/",
            "id"=>"27069377"
        ],
        [
            "rating"=>[
                "max"=>10,
                "average"=>0,
                "stars"=>"00",
                "min"=>0
            ],
            "genres"=>[
                "剧情"
            ],
            "title"=>"中国合伙人2",
            "casts"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1312817/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p14006.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p14006.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p14006.jpg"
                    ],
                    "name"=>"赵立新",
                    "id"=>"1312817"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1274651/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p5970.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p5970.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p5970.jpg"
                    ],
                    "name"=>"凌潇肃",
                    "id"=>"1274651"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1367682/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1501833870.86.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1501833870.86.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1501833870.86.jpg"
                    ],
                    "name"=>"王嘉",
                    "id"=>"1367682"
                ]
            ],
            "collect_count"=>27,
            "original_title"=>"中国合伙人2",
            "subtype"=>"movie",
            "directors"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1406262/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1544078893.81.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1544078893.81.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1544078893.81.jpg"
                    ],
                    "name"=>"刘亚当",
                    "id"=>"1406262"
                ]
            ],
            "year"=>"2018",
            "images"=>[
                "small"=>"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2540521849.jpg",
                "large"=>"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2540521849.jpg",
                "medium"=>"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2540521849.jpg"
            ],
            "alt"=>"https://movie.douban.com/subject/30293828/",
            "id"=>"30293828"
        ],
        [
            "rating"=>[
                "max"=>10,
                "average"=>0,
                "stars"=>"00",
                "min"=>0
            ],
            "genres"=>[
                "剧情"
            ],
            "title"=>"又是一年三月三",
            "casts"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1316135/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p35239.jpg",
                        "large"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p35239.jpg",
                        "medium"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p35239.jpg"
                    ],
                    "name"=>"刘之冰",
                    "id"=>"1316135"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1034637/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1415028031.49.jpg",
                        "large"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1415028031.49.jpg",
                        "medium"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1415028031.49.jpg"
                    ],
                    "name"=>"颜丹晨",
                    "id"=>"1034637"
                ],
                [
                    "alt"=>null,
                    "avatars"=>null,
                    "name"=>"孙亮 Liang Sun",
                    "id"=>null
                ]
            ],
            "collect_count"=>30,
            "original_title"=>"又是一年三月三",
            "subtype"=>"movie",
            "directors"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1323319/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p56186.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p56186.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p56186.jpg"
                    ],
                    "name"=>"马会雷",
                    "id"=>"1323319"
                ]
            ],
            "year"=>"2018",
            "images"=>[
                "small"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2532371671.jpg",
                "large"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2532371671.jpg",
                "medium"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2532371671.jpg"
            ],
            "alt"=>"https://movie.douban.com/subject/30214071/",
            "id"=>"30214071"
        ],
        [
            "rating"=>[
                "max"=>10,
                "average"=>0,
                "stars"=>"00",
                "min"=>0
            ],
            "genres"=>[
                "剧情"
            ],
            "title"=>"片警宝音",
            "casts"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1327202/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1539534032.51.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1539534032.51.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1539534032.51.jpg"
                    ],
                    "name"=>"宝音尼木胡",
                    "id"=>"1327202"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1351377/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1474279454.06.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1474279454.06.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1474279454.06.jpg"
                    ],
                    "name"=>"巴德玛",
                    "id"=>"1351377"
                ]
            ],
            "collect_count"=>45,
            "original_title"=>"片警宝音",
            "subtype"=>"movie",
            "directors"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1324598/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1361957648.15.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1361957648.15.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1361957648.15.jpg"
                    ],
                    "name"=>"杨瑾",
                    "id"=>"1324598"
                ]
            ],
            "year"=>"2018",
            "images"=>[
                "small"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541310016.jpg",
                "large"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541310016.jpg",
                "medium"=>"https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2541310016.jpg"
            ],
            "alt"=>"https://movie.douban.com/subject/30316976/",
            "id"=>"30316976"
        ],
        [
            "rating"=>[
                "max"=>10,
                "average"=>0,
                "stars"=>"00",
                "min"=>0
            ],
            "genres"=>[
                "动作",
                "科幻",
                "动画"
            ],
            "title"=>"蜘蛛侠：平行宇宙",
            "casts"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1350106/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1434437756.07.jpg",
                        "large"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1434437756.07.jpg",
                        "medium"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1434437756.07.jpg"
                    ],
                    "name"=>"沙梅克·摩尔",
                    "id"=>"1350106"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1316713/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1449582908.84.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1449582908.84.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1449582908.84.jpg"
                    ],
                    "name"=>"杰克·约翰逊",
                    "id"=>"1316713"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1312964/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p20419.jpg",
                        "large"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p20419.jpg",
                        "medium"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p20419.jpg"
                    ],
                    "name"=>"海莉·斯坦菲尔德",
                    "id"=>"1312964"
                ]
            ],
            "collect_count"=>972,
            "original_title"=>"Spider-Man=>Into the Spider-Verse",
            "subtype"=>"movie",
            "directors"=>[
                [
                    "alt"=>"https://movie.douban.com/celebrity/1310107/",
                    "avatars"=>[
                        "small"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1519064730.28.jpg",
                        "large"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1519064730.28.jpg",
                        "medium"=>"https://img1.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1519064730.28.jpg"
                    ],
                    "name"=>"鲍勃·佩尔西凯蒂",
                    "id"=>"1310107"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1324415/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p59042.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p59042.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p59042.jpg"
                    ],
                    "name"=>"彼得·拉姆齐",
                    "id"=>"1324415"
                ],
                [
                    "alt"=>"https://movie.douban.com/celebrity/1296189/",
                    "avatars"=>[
                        "small"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543307159.85.jpg",
                        "large"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543307159.85.jpg",
                        "medium"=>"https://img3.doubanio.com/view/celebrity/s_ratio_celebrity/public/p1543307159.85.jpg"
                    ],
                    "name"=>"罗德尼·罗斯曼",
                    "id"=>"1296189"
                ]
            ],
            "year"=>"2018",
            "images"=>[
                "small"=>"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2541839958.jpg",
                "large"=>"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2541839958.jpg",
                "medium"=>"https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2541839958.jpg"
            ],
            "alt"=>"https://movie.douban.com/subject/26374197/",
            "id"=>"26374197"
        ]
    ],
    "title"=>"即将上映的电影"
];

$param = $_POST;
// var_dump($param);
$page = isset($param['page']) ? $param['page'] : 1;
$pageSize = isset($param['pageSize']) ? $param['pageSize'] : 5;

$start = ($page-1) * $pageSize;
$returnMovie = [];
if($start < count($movies['subjects'])){
    $returnMovie = array_slice($movies['subjects'],$start,$pageSize);
    // var_dump($start);
    // var_dump($pageSize);
}

$movies['subjects'] = $returnMovie;
$movies['count'] = count($returnMovie);

echo json_encode($movies);